### ISSUE TITLE
Cannot read properties of undefined (reading 'max')

### ISSUE THREAD

**Issue by asqararslonov** [esnz/reactweather#1]
![image](https://user-images.githubusercontent.com/69717101/136031693-3c1f0fb5-0721-424c-bc6e-e763ba0f3d3d.png)

I'm trying to run your weather app on my computer but I get this error.

**Comment by esnz** [comment]
Did you set your OpenWeatherMap API key in the .env file? 
If you didn't, you should create an account on the OpenWeatherMap website to get an API key.
