### ISSUE TITLE
Place Suggestions API is not working

### ISSUE THREAD

**Issue by DixitLathiya123** [esnz/reactweather#3]
![image](https://user-images.githubusercontent.com/73575992/233070361-26339989-7e82-4185-8bd2-c1554880c7fc.png)
![image](https://user-images.githubusercontent.com/73575992/233070473-8a700a75-8c43-492c-a3d5-d3275b340b2e.png)

**Comment by esnz** [comment]
Algolia has shutdown its place suggestion feature, I'll update the project once I find a good alternative.
https://www.algolia.com/blog/product/sunsetting-our-places-feature/
